#!/usr/bin/env bash

mkdir nixpkgs
cd nixpkgs
git init
git sparse-checkout init
git sparse-checkout set "pkgs/applications/networking/browsers/chromium"
git sparse-checkout add "pkgs/applications/graphics/krita"
git fetch https://github.com/NixOS/nixpkgs nixos-23.11 --depth 1
git branch nixos-23.11 FETCH_HEAD
git checkout nixos-23.11
